POST http://localhost:8080/api/1.0/NotesRate
Content-Type: application/json

{
    "noteNumber": 33,
    "videoNoteNumber": 31,
    "hundredLikePercent": "84.8",
    "thousandLikePercent": "54.5",
    "noteType": [
      {
        "contentTag": "时尚",
        "percent": "87.9"
      },
      {
        "contentTag": "出行旅游",
        "percent": "6.1"
      }
    ],
    "tradeNames": null,
    "impMedian": 313411,
    "impMedianBeyondRate": "90.0",
    "readMedian": 53676,
    "readMedianBeyondRate": "89.0",
    "interactionMedian": 1952,
    "interactionRate": "8.6",
    "interactionBeyondRate": "85.3",
    "likeMedian": 1309,
    "collectMedian": 566,
    "commentMedian": 77,
    "shareMedian": 69,
    "videoFullViewRate": "17.1",
    "videoFullViewBeyondRate": "58.5",
    "picture3sViewRate": "74.5",
    "notes": [
      {
        "noteId": "667a96b2000000001d01941b",
        "date": null,
        "publishTime": "2024-06-25",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314fcqgdv68004b7opnjldtic3kj3b68?imageView2/2/w/540/format/jpg/q/75",
        "title": "度假泳衣👙南法吸睛出片神器/绝美显白显瘦！",
        "canJump": true,
        "impNum": 7931403,
        "impBeyondRate": 24.306,
        "readNum": 1518777,
        "readBeyondRate": 27.295,
        "interactionNum": 153480,
        "interactionBeyondRate": 77.627,
        "collectNum": 42324,
        "likeNum": 83601,
        "collectBeyondRate": 73.777,
        "likeBeyondRate": 62.866
      },
      {
        "noteId": "667c01eb000000001c037105",
        "date": null,
        "publishTime": "2024-06-26",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g2sg314gpcqav6e004b7opnjldtic5qc75do?imageView2/2/w/540/format/jpg/q/75",
        "title": "夏日气息的清爽配色💦4套蓝色短裙/衬衫/T恤",
        "canJump": true,
        "impNum": 400679,
        "impBeyondRate": 0.278,
        "readNum": 62039,
        "readBeyondRate": 0.155,
        "interactionNum": 2940,
        "interactionBeyondRate": 0.506,
        "collectNum": 683,
        "likeNum": 1627,
        "collectBeyondRate": 0.206,
        "likeBeyondRate": 0.242
      },
      {
        "noteId": "667d5c65000000001c036e17",
        "date": null,
        "publishTime": "2024-06-27",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314i3ifvv6k004b7opnjldticp2eeuqg?imageView2/2/w/540/format/jpg/q/75",
        "title": "10双🩰近期爱穿鞋子！凉鞋/拖鞋/高跟/运动鞋",
        "canJump": true,
        "impNum": 288391,
        "impBeyondRate": -0.079,
        "readNum": 39699,
        "readBeyondRate": -0.26,
        "interactionNum": 1534,
        "interactionBeyondRate": -0.214,
        "collectNum": 415,
        "likeNum": 913,
        "collectBeyondRate": -0.266,
        "likeBeyondRate": -0.302
      },
      {
        "noteId": "667e9953000000001c02094b",
        "date": null,
        "publishTime": "2024-06-28",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g2sg314ja2e8gme704b7opnjldticbn8kbp8?imageView2/2/w/540/format/jpg/q/75",
        "title": "少女感攻击🧋3套清爽甜而不腻奶茶味小裙子！",
        "canJump": true,
        "impNum": 455789,
        "impBeyondRate": 0.454,
        "readNum": 76788,
        "readBeyondRate": 0.43,
        "interactionNum": 3481,
        "interactionBeyondRate": 0.783,
        "collectNum": 868,
        "likeNum": 2034,
        "collectBeyondRate": 0.533,
        "likeBeyondRate": 0.553
      },
      {
        "noteId": "66800a28000000001d016f1e",
        "date": null,
        "publishTime": "2024-06-29",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314lpb94vmg004b7opnjldticnip4k6o?imageView2/2/w/540/format/jpg/q/75",
        "title": "去班味的明艳度假感🍷4套浓人热情南法穿搭~",
        "canJump": true,
        "impNum": 263232,
        "impBeyondRate": -0.16,
        "readNum": 40561,
        "readBeyondRate": -0.244,
        "interactionNum": 1576,
        "interactionBeyondRate": -0.192,
        "collectNum": 388,
        "likeNum": 913,
        "collectBeyondRate": -0.314,
        "likeBeyondRate": -0.302
      },
      {
        "noteId": "66813022000000001d01bc37",
        "date": null,
        "publishTime": "2024-06-30",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314lpb94vmg1g4b7opnjldticltuv2a0?imageView2/2/w/540/format/jpg/q/75",
        "title": "穿彩色过夏天了哦✨永远爱温柔又吸睛的裙子~",
        "canJump": true,
        "impNum": 59082,
        "impBeyondRate": -0.811,
        "readNum": 10902,
        "readBeyondRate": -0.796,
        "interactionNum": 450,
        "interactionBeyondRate": -0.769,
        "collectNum": 108,
        "likeNum": 281,
        "collectBeyondRate": -0.809,
        "likeBeyondRate": -0.785
      },
      {
        "noteId": "6681506c000000001d0197fc",
        "date": null,
        "publishTime": "2024-06-30",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314lpb94vmg6g4b7opnjldticva5cfbo?imageView2/2/w/540/format/jpg/q/75",
        "title": "穿彩色也太开心了吧！🍑4套低饱和度显白裙裙",
        "canJump": true,
        "impNum": 6627,
        "impBeyondRate": -0.978,
        "readNum": 1056,
        "readBeyondRate": -0.98,
        "interactionNum": 31,
        "interactionBeyondRate": -0.984,
        "collectNum": 7,
        "likeNum": 21,
        "collectBeyondRate": -0.987,
        "likeBeyondRate": -0.983
      },
      {
        "noteId": "66826fe80000000003026139",
        "date": null,
        "publishTime": "2024-07-01",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g2sg314n1k3h7me004b7opnjldtict836qjo?imageView2/2/w/540/format/jpg/q/75",
        "title": "油画感穿搭🍃4️⃣套亮眼不浮夸私藏套装裙~",
        "canJump": true,
        "impNum": 265780,
        "impBeyondRate": -0.151,
        "readNum": 40277,
        "readBeyondRate": -0.249,
        "interactionNum": 1717,
        "interactionBeyondRate": -0.12,
        "collectNum": 435,
        "likeNum": 991,
        "collectBeyondRate": -0.231,
        "likeBeyondRate": -0.242
      },
      {
        "noteId": "6683c7aa000000000a005be9",
        "date": null,
        "publishTime": "2024-07-02",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g2sg314oc84dcg6704b7opnjldticf3f176g?imageView2/2/w/540/format/jpg/q/75",
        "title": "太爱穿彩色衣服过夏天啦！🩰温柔的低饱和色",
        "canJump": true,
        "impNum": 209474,
        "impBeyondRate": -0.331,
        "readNum": 38599,
        "readBeyondRate": -0.28,
        "interactionNum": 1297,
        "interactionBeyondRate": -0.335,
        "collectNum": 330,
        "likeNum": 762,
        "collectBeyondRate": -0.416,
        "likeBeyondRate": -0.417
      },
      {
        "noteId": "66866f2f00000000030243e9",
        "date": null,
        "publishTime": "2024-07-04",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g2sg314qta6t71c704b7opnjldtichktbkog?imageView2/2/w/540/format/jpg/q/75",
        "title": "有点长的购物分享🖤下饭看！我也太会买噜！！",
        "canJump": true,
        "impNum": 249699,
        "impBeyondRate": -0.203,
        "readNum": 31708,
        "readBeyondRate": -0.409,
        "interactionNum": 1401,
        "interactionBeyondRate": -0.282,
        "collectNum": 205,
        "likeNum": 846,
        "collectBeyondRate": -0.637,
        "likeBeyondRate": -0.353
      },
      {
        "noteId": "668744f200000000050078de",
        "date": null,
        "publishTime": "2024-07-05",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314rpcmj91c004b7opnjldticevn41i0?imageView2/2/w/540/format/jpg/q/75",
        "title": "记录下26岁的这一刻,给86岁的自己看",
        "canJump": true,
        "impNum": 160221,
        "impBeyondRate": -0.488,
        "readNum": 35763,
        "readBeyondRate": -0.333,
        "interactionNum": 1287,
        "interactionBeyondRate": -0.34,
        "collectNum": 163,
        "likeNum": 968,
        "collectBeyondRate": -0.712,
        "likeBeyondRate": -0.26
      },
      {
        "noteId": "6688be52000000000d00e1a8",
        "date": null,
        "publishTime": "2024-07-06",
        "type": 1,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314t74v6ch41g4b7opnjldtic2mlgr30?imageView2/2/w/540/format/jpg/q/75",
        "title": "发点朋友圈品不了的细糠",
        "canJump": true,
        "impNum": 225556,
        "impBeyondRate": -0.28,
        "readNum": 50968,
        "readBeyondRate": -0.05,
        "interactionNum": 2396,
        "interactionBeyondRate": 0.227,
        "collectNum": 350,
        "likeNum": 1625,
        "collectBeyondRate": -0.381,
        "likeBeyondRate": 0.241
      },
      {
        "noteId": "668a7b960000000005006c76",
        "date": null,
        "publishTime": "2024-07-07",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g008314uqsjmegu3g4b7opnjldticjohu3lg?imageView2/2/w/540/format/jpg/q/75",
        "title": "14个私藏出行好物！旅行变美神器🫶🏻无广！",
        "canJump": true,
        "impNum": 178030,
        "impBeyondRate": -0.431,
        "readNum": 20852,
        "readBeyondRate": -0.611,
        "interactionNum": 1614,
        "interactionBeyondRate": -0.173,
        "collectNum": 527,
        "likeNum": 929,
        "collectBeyondRate": -0.068,
        "likeBeyondRate": -0.29
      },
      {
        "noteId": "668bbf980000000005006863",
        "date": null,
        "publishTime": "2024-07-08",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g00831505aam0ha004b7opnjldticfbvqme0?imageView2/2/w/540/format/jpg/q/75",
        "title": "在夏天盛放的生命力🌹显白热烈的玫瑰红色~",
        "canJump": true,
        "impNum": 206658,
        "impBeyondRate": -0.34,
        "readNum": 33735,
        "readBeyondRate": -0.371,
        "interactionNum": 2371,
        "interactionBeyondRate": 0.214,
        "collectNum": 641,
        "likeNum": 1445,
        "collectBeyondRate": 0.132,
        "likeBeyondRate": 0.103
      },
      {
        "noteId": "668d095c000000000a026798",
        "date": null,
        "publishTime": "2024-07-09",
        "type": 2,
        "imgUrl": "http://ci.xiaohongshu.com/1040g2sg3151dfhrn1e704b7opnjldtich8v7kjg?imageView2/2/w/540/format/jpg/q/75",
        "title": "矜贵感ootd西装裙套装🩰小正式场合不费力~",
        "canJump": true,
        "impNum": 91884,
        "impBeyondRate": -0.706,
        "readNum": 14032,
        "readBeyondRate": -0.738,
        "interactionNum": 814,
        "interactionBeyondRate": -0.582,
        "collectNum": 201,
        "likeNum": 509,
        "collectBeyondRate": -0.644,
        "likeBeyondRate": -0.611
      }
    ],
    "pagePercentVo": {
      "impHomefeedPercent": 0.716,
      "impSearchPercent": 0.077,
      "impFollowPercent": 0.05,
      "impDetailPercent": 0.134,
      "impNearbyPercent": 0,
      "impOtherPercent": 0.02300000000000002,
      "readHomefeedPercent": 0.664,
      "readSearchPercent": 0.075,
      "readFollowPercent": 0.099,
      "readDetailPercent": 0.136,
      "readNearbyPercent": 0,
      "readOtherPercent": 0.02599999999999994
    },
    "longTermCommonNoteVo": {
      "startPublishTime": "2023-11-14",
      "endPublishTime": "2024-01-13",
      "noteNumber": 42,
      "recentReadNum": 58479,
      "recentReadBeyondRate": "70.5",
      "longTermReadNum": 12446,
      "longTermReadBeyondRate": "76.7",
      "recentSearchPagePercent": "9.0",
      "recentFindPagePercent": "47.8",
      "recentKolHomePagePercent": "8.7",
      "recentFollowPagePercent": "32.2",
      "recentOtherPagePercent": "2.3",
      "longTermSearchPagePercent": "58.2",
      "longTermFindPagePercent": "6.1",
      "longTermKolHomePagePercent": "28.8",
      "longTermFollowPagePercent": "0.6",
      "longTermOtherPagePercent": "6.3"
    },
    "longTermCooperateNoteVo": {
      "startPublishTime": "2023-11-14",
      "endPublishTime": "2024-01-13",
      "noteNumber": 4,
      "recentReadNum": 53462,
      "recentReadBeyondRate": "78.6",
      "longTermReadNum": 7871,
      "longTermReadBeyondRate": "74.7",
      "recentSearchPagePercent": "6.6",
      "recentFindPagePercent": "42.6",
      "recentKolHomePagePercent": "12.4",
      "recentFollowPagePercent": "35.9",
      "recentOtherPagePercent": "2.5",
      "longTermSearchPagePercent": "14.4",
      "longTermFindPagePercent": "5.0",
      "longTermKolHomePagePercent": "65.1",
      "longTermFollowPagePercent": "1.0",
      "longTermOtherPagePercent": "14.5"
    },
    "mEngagementNum": 2171,
    "mFollowCnt": 172
  }

###
