POST http://localhost:8080/api/1.0/plugin-items
Content-Type: application/json
Accept-Language: zh-cn

{
  "shopId": "105703949",
  "shopName": "TT坏坏",
  "shopUrl": "https://shop105703949.taobao.com",
  "items": [
    {
      "itemId": "779612411768",
      "name": "TT坏坏针织无袖长裙搭配吊带裙两件套女休闲度假风宽松设计感套装",
      "saleNum": "1000+"
    },
    {
      "itemId": "782884188951",
      "name": "TT坏坏 夏季新款粉色百褶高腰针织半身裙女修身显瘦小个子a字短裙",
      "saleNum": "900+"
    },
    {
      "itemId": "779321624823",
      "name": "TT坏坏 夏季新款米白色短袖针织上衣女修身显瘦百搭薄款凉T恤上衣",
      "saleNum": "900+"
    },
    {
      "itemId": "778137410338",
      "name": "TT坏坏2024夏季新款韩版灰色高腰半身裙女时尚百搭显瘦气质西装裙",
      "saleNum": "700+"
    },
    {
      "itemId": "778168413244",
      "name": "TT坏坏 2024圆领正肩短袖修身T恤夏季新品薄款套头百搭短款上衣女",
      "saleNum": "500+"
    },
    {
      "itemId": "780899662676",
      "name": "TT坏坏蓝色高腰显瘦气质半身裙女2024夏季新款韩版时尚设计感裙子",
      "saleNum": "500+"
    },
    {
      "itemId": "780862279126",
      "name": "TT坏坏 蓝色毛针织短袖女2024夏季新款温柔风正肩T恤修身显瘦上衣",
      "saleNum": "400+"
    },
    {
      "itemId": "775054956968",
      "name": "TT坏坏夏季新品韩版长袖薄款条纹两色防晒衫休闲宽松设计感上衣女",
      "saleNum": "500+"
    },
    {
      "itemId": "766656931825",
      "name": "TT坏坏 白色休闲长裤女2024初春新款韩版薄款百搭高腰垂感直筒裤",
      "saleNum": "200+"
    },
    {
      "itemId": "781223482290",
      "name": "TT坏坏 粉色薄针织短袖女2024夏季新款温柔风正肩T恤修身显瘦上衣",
      "saleNum": "200+"
    },
    {
      "itemId": "781182095513",
      "name": "TT坏坏 休闲凉凉裤女2024夏季新款韩版薄款百搭高腰直筒长裤",
      "saleNum": "200+"
    },
    {
      "itemId": "735500065981",
      "name": "【春夏秋~断码清仓集合~】现货秒发~",
      "saleNum": "200+"
    },
    {
      "itemId": "780840109109",
      "name": "TT坏坏 2024夏季新品薄款防晒开衫女度假休闲百搭设计感外套上衣",
      "saleNum": "100+"
    },
    {
      "itemId": "783167386615",
      "name": "TT坏坏 米黄色吊带度假风裙女夏季新款内搭裙显瘦修身长款连衣裙",
      "saleNum": "100+"
    },
    {
      "itemId": "780838317515",
      "name": "TT坏坏 夏季新品韩版无袖吊带中长款连衣裙女修身显瘦度假风长裙",
      "saleNum": "100+"
    },
    {
      "itemId": "774836375427",
      "name": "TT坏坏 白色蕾丝花边纯欲修身百搭定制吊带女高级感韩系打底背心",
      "saleNum": "100+"
    },
    {
      "itemId": "766552436238",
      "name": "TT坏坏春季新款蓝色针织开衫女时尚宽松百搭显瘦薄款长袖温柔上衣",
      "saleNum": "100+"
    },
    {
      "itemId": "783727725237",
      "name": "TT坏坏 夏季新品挂脖系带背心吊带女修身显瘦高级感内搭无袖上衣",
      "saleNum": "100+"
    },
    {
      "itemId": "778494508788",
      "name": "TT坏坏 2024夏季新款薄款紫色防晒开衫女宽松休闲韩版设计感外套",
      "saleNum": "100+"
    },
    {
      "itemId": "784523305209",
      "name": "TT坏坏韩版蓝色无袖吊带连衣裙女夏季新款度假风修身显瘦百搭长裙",
      "saleNum": "100+"
    },
    {
      "itemId": "775387734412",
      "name": "TT坏坏2024夏季新品高腰显瘦白色半身裙女时尚气质百搭小个子短裙",
      "saleNum": "100+"
    },
    {
      "itemId": "784320511488",
      "name": "TT坏坏 条纹高腰阔腿短裤女夏季新品休闲时尚小个子百搭通勤短裤",
      "saleNum": "100+"
    },
    {
      "itemId": "741442172705",
      "name": "【夏款~断码清仓集合~】现货秒发~清仓区~",
      "saleNum": "100+"
    },
    {
      "itemId": "767742837785",
      "name": "TT坏坏 2024春装紫色长袖薄款宽松针织圆领套头衫女韩系休闲上衣",
      "saleNum": "91"
    }
  ]
}

###
