POST http://localhost:8080/api/1.0/plugin-items
Content-Type: application/json
Accept-Language: zh-cn

{
  "shopId": "105703949",
  "shopName": "TT坏坏",
  "publishedAt": "2024-04-15",
  "shopUrl": "https://shop105703949.taobao.com",
  "parentCatId": 1772652848,
  "parentCatName": "6月新品",
  "catId": 1779767080,
  "catName": "06/25福利回馈",
  "items": [
    {
      "itemId": "792189876642",
      "name": "TT坏坏 夏季新款无袖长款做旧连衣裙女宽松显瘦免水洗牛仔背带裙",
      "saleNum": "17",
      "pic": "https://img.alicdn.com/bao/uploaded/i1/548131171/O1CN01X2vnd71KWMkVf53bM_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "790355450598",
      "name": "TT坏坏 2024夏新品ins小清新碎花韩版直筒高腰显瘦阔腿裤女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i4/548131171/O1CN013Wzuss1KWMkLTeTLA_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "790353882290",
      "name": "TT坏坏 2024年夏季新款假两件短袖正肩T恤韩系修身显瘦设计感上衣",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i1/548131171/O1CN014dm4Jc1KWMkL1rfPa_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "790450336720",
      "name": "TT坏坏 白色芭蕾风纯欲甜美收腰显瘦吊带连衣裙公主A字短裙子女夏",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN01yXAEA61KWMkJRdguT_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "790447864759",
      "name": "TT坏坏 韩系温柔风薄荷绿圆领袖口抽绳设计感短款小衫女夏季",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i1/548131171/O1CN01LcxhXv1KWMkLTjZfw_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789877415155",
      "name": "TT坏坏 法式吊带连衣裙女温柔风修身大摆长裙搭配防晒小外套夏季",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN01QTroSl1KWMkIySdEW_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "790017617375",
      "name": "TT坏坏 灰色高腰抽绳半身裙女夏季运动风短款防走光包臀a字短裙女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN0104xDSe1KWMkMGj5RV_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789874387993",
      "name": "TT坏坏 白色麻花薄款针织短袖上衣小个子百搭短款日常通勤小衫",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i3/548131171/O1CN01D5ocw61KWMkMvqaLa_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "790019740516",
      "name": "TT坏坏 甜美粉色无袖背心花苞上衣半身裙两件套百搭设计感套装女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i4/548131171/O1CN01mxSUN31KWMkLXOV3I_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789360107634",
      "name": "TT坏坏 蓝条纹薄款针织套装女polo领无袖背心半身裙气质两件套夏",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN018PzjFW1KWMkExp0uG_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789469944159",
      "name": "TT坏坏 2024年夏季短袖简约基础简单T恤美式休闲宽松字母上衣女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i3/548131171/O1CN01YVvu9y1KWMkES778P_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789374498779",
      "name": "TT坏坏 碎花半身裙女法式复古气质高腰显瘦小众设计感中长裙女夏",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i4/548131171/O1CN01oWBjfE1KWMkES7zF1_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789139204951",
      "name": "TT坏坏 小个子缎面波点短裙夏季新款薄款修身气质百搭半身裙女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i1/548131171/O1CN01agpgnO1KWMkHgnEah_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789002263577",
      "name": "TT坏坏 法式气质U领冰丝针织薄款短袖上衣修身显瘦别致短款小衫",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i3/548131171/O1CN01voX8LL1KWMkKCjXMN_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789136813484",
      "name": "TT坏坏 韩版波点印花泡泡袖连衣裙v领收腰显瘦气质百搭a字长裙女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i4/548131171/O1CN01YRwbhV1KWMkCb5xuj_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789134848216",
      "name": "TT坏坏 法式碎花吊带连衣裙2024夏季新款气质收腰显瘦度假风长裙",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i1/548131171/O1CN01Y2G1mR1KWMkFS41bR_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789133424862",
      "name": "TT坏坏 防晒衬衫女2024夏季新款后背系带设计感宽松休闲长袖开衫",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN01SVOA3x1KWMkJYPFPk_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "789132273177",
      "name": "TT坏坏 休闲多巴胺防晒棉麻衬衫2024夏季宽松薄款长袖衬衣外套女",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i1/548131171/O1CN01arMfUd1KWMkIoRavG_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "788765761021",
      "name": "TT坏坏 夏季薄款衬衫女2024新款韩版通勤宽松长袖设计感百搭外套",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i4/548131171/O1CN01K1sJ2b1KWMkF9jFEm_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "788631979880",
      "name": "TT坏坏 灰色无袖背心连衣裙女夏季2024新款收腰显瘦气质吊带长裙",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i3/548131171/O1CN01Hm8Lmi1KWMkEgtyg4_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "788630783344",
      "name": "TT坏坏 法式温柔风气质抹胸小吊带背心女百搭显瘦设计感修身外穿",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN01xNJj9i1KWMkHkEvhg_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "784753858680",
      "name": "TT坏坏 夏季新款假日碎花吊带连衣裙女甜美叠穿收腰A字大摆长裙女",
      "saleNum": "79",
      "pic": "https://img.alicdn.com/bao/uploaded/i3/548131171/O1CN01JIARIr1KWMkSsDdgG_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "784715755014",
      "name": "TT坏坏 女夏季新款韩版薄款百搭高腰修身显瘦微喇裤牛仔长裤",
      "saleNum": "46",
      "pic": "https://img.alicdn.com/bao/uploaded/i4/548131171/O1CN01mTcBoO1KWMkZfy7u6_!!548131171.jpg_240x240.jpg"
    },
    {
      "itemId": "784714151500",
      "name": "TT坏坏 度假风吊带上衣女2024年夏季不规则花边设计高级感小衫",
      "saleNum": "0",
      "pic": "https://img.alicdn.com/bao/uploaded/i2/548131171/O1CN01GA16tX1KWMk3qPjUr_!!548131171.jpg_240x240.jpg"
    }
  ]
}

###
